// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVw0bbR_i-EPCJZfCjBImrFkt7GTqc-t4',
    appId: '1:221823459595:web:f7805b65aff7d74d86c20e',
    messagingSenderId: '221823459595',
    projectId: 'onepager-38009',
    authDomain: 'onepager-38009.firebaseapp.com',
    storageBucket: 'onepager-38009.firebasestorage.app',
    measurementId: 'G-L2DYPTTD0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1AW45wawqYQ72E3-nA8V5OkOgzKd4kg8',
    appId: '1:221823459595:android:e2d17e39b5abedde86c20e',
    messagingSenderId: '221823459595',
    projectId: 'onepager-38009',
    storageBucket: 'onepager-38009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy-mlaD6vtK4ilwR6KP3T2y-b2rSk9IG8',
    appId: '1:221823459595:ios:cc3c0e61e178634486c20e',
    messagingSenderId: '221823459595',
    projectId: 'onepager-38009',
    storageBucket: 'onepager-38009.firebasestorage.app',
    iosBundleId: 'com.example.flutterSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy-mlaD6vtK4ilwR6KP3T2y-b2rSk9IG8',
    appId: '1:221823459595:ios:cc3c0e61e178634486c20e',
    messagingSenderId: '221823459595',
    projectId: 'onepager-38009',
    storageBucket: 'onepager-38009.firebasestorage.app',
    iosBundleId: 'com.example.flutterSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVw0bbR_i-EPCJZfCjBImrFkt7GTqc-t4',
    appId: '1:221823459595:web:aba46bc4b3a8036286c20e',
    messagingSenderId: '221823459595',
    projectId: 'onepager-38009',
    authDomain: 'onepager-38009.firebaseapp.com',
    storageBucket: 'onepager-38009.firebasestorage.app',
    measurementId: 'G-32EW37YZ1D',
  );
}
